name: qip-encoding-study
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - PennyLane==0.44.1
      - torch==2.6.0
      - torchvision==0.21.0
      - numpy==2.4.3
      - scikit-learn==1.8.0
      - matplotlib==3.10.8
      - seaborn==0.13.2
